# Generated by Django 4.2.8 on 2023-12-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_instance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='started_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='stopped_at',
            field=models.TimeField(),
        ),
    ]
