# Generated by Django 4.2.8 on 2023-12-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_instance', '0002_alter_taskinstance_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
