# Generated by Django 4.2.8 on 2023-12-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_instance', '0003_taskinstance_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
