# Generated by Django 4.2.8 on 2023-12-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_instance", "0004_taskinstance_billable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="duration_worked",
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="stopped_at",
            field=models.TimeField(default=models.TimeField()),
        ),
    ]
