# Generated by Django 4.2.8 on 2023-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_instance", "0005_alter_taskinstance_duration_worked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="started_at",
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="stopped_at",
            field=models.TimeField(default=0),
        ),
    ]
