# Generated by Django 4.2.8 on 2023-12-31 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_instance", "0007_alter_taskinstance_billable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="started_at",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="stopped_at",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
