# Generated by Django 4.2.8 on 2023-12-31 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_instance", "0008_alter_taskinstance_started_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="duration_worked",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
