# Generated by Django 4.2.8 on 2024-03-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_instance", "0010_alter_taskinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskinstance",
            options={
                "permissions": [
                    ("start_task_instance", "Can start task instance"),
                    ("stop_task_instance", "Can stop a task instance"),
                ]
            },
        ),
    ]
