version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasktracez-backend
    container_name: tasktracez-backend
    command: sh -c "python manage.py migrate && if [ \"$ENV\" = \"dev\" ]; then python manage.py loaddata */fixtures/*.yaml; fi && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:latest
    container_name: tasktracez-database
    env_file:
      - .env.database
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]

volumes:
  database-data:
