version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasktracez-backend
    container_name: tasktracez-backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:latest
    container_name: tasktracez-mysql
    env_file:
      - .env.database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
