# Generated by Django 4.2.8 on 2023-12-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_description_alter_project_title'),
        ('task', '0002_rename_name_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'project')},
        ),
    ]
