# Generated by Django 4.2.8 on 2024-03-04 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_projectuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectuser",
            options={"permissions": [("add_user", "Can add user")]},
        ),
    ]
