# Generated by Django 4.2.8 on 2024-03-04 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_projectuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectuser",
            options={},
        ),
    ]
